name: flutter_assignment
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  http: ^1.1.2
  url_launcher: ^6.2.2

  





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
  mocktail: ^0.3.0



flutter:
  uses-material-design: true
fonts:
    - family: Lato
      fonts:
        - asset: assets/font/Lato-Bold.ttf
          style: Bold